### ISSUE TITLE
problems with getTermProps since Hyper 1.3.2

### ISSUE THREAD

**Issue by iamstarkov** [chabou/hyper-pane#11]
```
bundle.js:1 TypeError: Cannot read property 'indexOf' of undefined
    at exports.getTermProps (/Users/iamstarkov/.hyper_plugins/node_modules/hyper-pane/index.js:323:36)
    at pe.forEach.fe (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:1:4407)
    at Array.forEach (native)
    at getProps (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:1:4350)
    at TermGroup_.renderTerm (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:5:3046)
    at D._renderValidatedComponentWithoutOwnerOrContext (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:47:300622)
    at D._renderValidatedComponent (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:47:300754)
    at D._updateRenderedComponent (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:47:300035)
    at D._performComponentUpdate (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:47:299824)
    at D.updateComponent (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:47:299045)
```

how do i provide more info?

**Comment by chabou** [comment]
When does it occur ? I can't reproduce

**Comment by iamstarkov** [comment]
pretty much every time: new tab, clear, split pane, remove pane

**Comment by iamstarkov** [comment]
split pane gives 50 errors from hyper-pane exactly

**Comment by iamstarkov** [comment]
give me a sec, will try with just hyper-pane

**Comment by shortjared** [comment]
I can confirm I also see this.

**Comment by iamstarkov** [comment]
one clarification: it works, but with shit tons of error notifications

**Comment by shortjared** [comment]
Mine never actually works, I left it go and got up to 600+ errors

**Comment by chabou** [comment]
Be sure to use last release of this plugin.
Can you give me your config file?

**Comment by nathanmalishev** [comment]
I had a similar issue of hyper term freezing out, after updating to 1.3.2, due to getTermProps. Tried the `plugins update all`, didn't work.
But what fixed my issue was removing it as a plugin & re-adding it. I guess that updated it properly.

**Comment by nshoes** [comment]
Can confirm, also happening to me. On latest Hyper and hyper-pane. Here's my config:

```
module.exports = {
  config: {
    fontSize: 12,

    fontFamily: 'Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',

    cursorColor: 'rgba(248,28,229,0.8)',

    cursorShape: 'UNDERLINE',

    foregroundColor: '#fff',

    backgroundColor: '#000',

    borderColor: '#333',

    css: '',

    termCSS: '',

    showHamburgerMenu: '',

    showWindowControls: '',

    padding: '12px 14px',

    colors: {
      black: '#000000',
      red: '#ff0000',
      green: '#33ff00',
      yellow: '#ffff00',
      blue: '#0066ff',
      magenta: '#cc00ff',
      cyan: '#00ffff',
      white: '#d0d0d0',
      lightBlack: '#808080',
      lightRed: '#ff0000',
      lightGreen: '#33ff00',
      lightYellow: '#ffff00',
      lightBlue: '#0066ff',
      lightMagenta: '#cc00ff',
      lightCyan: '#00ffff',
      lightWhite: '#ffffff'
    },

    shell: '',

    shellArgs: ['--login'],

    env: {},

    bell: 'SOUND',

    copyOnSelect: false,

    paneNavigation: {
      debug: false,
      hotkeys: {
        navigation: {
          up: 'command+ctrl+k',
          down: 'command+ctrl+j',
          left: 'command+ctrl+h',
          right: 'command+ctrl+l'
        },
        jump_prefix: 'ctrl+alt',
        permutation_modifier: 'shift',
      },
      showIndicators: false,
      indicatorPrefix: '',
      indicatorStyle: {
        position: 'absolute',
        top: 0,
        left: 0,
        fontSize: '10px'
      },
      focusOnMouseHover: false
    }
  },

  plugins: ['hyper-nord', 'hyper-pane'],

  localPlugins: []
};
```

**Comment by nshoes** [comment]
It occurs for me when I'm creating a new pane. No new pane shows up, and I get 16 of the originally reported errors in a row.

**Comment by chabou** [comment]
I think that your issue is fixed. Please comment if not
